spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: matem2003
    url: jdbc:postgresql://localhost:5432/itransition_task4
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always